name: Build & Deploy Docs (TypeDoc → GitHub Pages)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Required for Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Only one Pages deploy at a time
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build docs (TypeDoc)
        run: npm run docs
        # TypeDoc outputs to ./docs by default. If you changed outDir, update the path below.

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
